// Generated by CoffeeScript 1.9.3
(function() {
  describe("Hello Karma Test", function() {
    return it("is first assertion", function() {
      return expect(true).toBe(false);
    });
  });

}).call(this);
