// Generated by CoffeeScript 1.9.3
(function() {
  var $extWrapper;

  $extWrapper = $('<div>').attr('id', 'ext-wrapper');

  $('body').append($extWrapper);

  $extWrapper.load(chrome.extension.getURL("contentScript/contentScript.html"), function() {
    return new extBackboneApp.AppView();
  });

}).call(this);
