// Generated by CoffeeScript 1.9.3
(function() {
  $.get(chrome.extension.getURL("contentScript/contentScript.html"), function(html) {
    return $('body').append($(html));
  });

  chrome.runtime.onMessage.addListener(function(request, sender, callback) {
    switch (request.type) {
      case "popup#appOn":
        if (!app.appView) {
          app.appView = new app.AppView({
            el: $("<div>")
          });
          return $("#ext-content").append(app.appView.$el);
        }
        break;
      case "popup#appOff":
        if (app.appView) {
          app.appView.remove();
          return app.appView = null;
        }
        break;
      case "popup#appReset":
        if (app.appView) {
          app.appView.remove();
          app.appView = new app.AppView({
            el: $("<div>")
          });
          return $("#ext-content").append(app.appView.$el);
        }
    }
  });

}).call(this);
