// Generated by CoffeeScript 1.9.3
(function() {
  var create_category, d, init_categories, word_search;

  d = function(str) {
    return $(".message").append(str);
  };

  create_category = function() {
    var fd, xhr;
    fd = new FormData();
    fd.append("category[name]", $("#category_name").val());
    xhr = new XMLHttpRequest();
    xhr.open("POST", "http://often-test-app.xyz:3005/categories.json", true);
    xhr.onload = function() {
      var obj;
      obj = $.parseJSON(xhr.responseText);
      $("#category_list").append($("<option>").val(obj.id).text(obj.name));
      $("#category_list").val(obj.id);
      return chrome.storage.sync.set({
        cat: obj.name,
        cat_id: obj.id
      }, function() {
        return $(".message").text("destination is set to " + obj.name + ".");
      });
    };
    xhr.onerror = function() {
      return callback("failure");
    };
    return xhr.send(fd);
  };

  init_categories = function() {
    var xhr;
    xhr = new XMLHttpRequest();
    xhr.open("GET", "http://often-test-app.xyz:3005/categories.json", true);
    xhr.onload = function() {
      $.parseJSON(xhr.responseText).forEach(function(c) {
        return $("#category_list").append($("<option>").val(c.id).text(c.name));
      });
      return chrome.storage.sync.get({
        cat: "uncategorized",
        cat_id: 8
      }, function(items) {
        return $("#category_list").val(items.cat_id);
      });
    };
    xhr.onerror = function() {
      return callback("failure");
    };
    return xhr.send();
  };

  word_search = function() {
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      return chrome.tabs.sendMessage(tabs[0].id, {
        type: "popup: word_search",
        word: $("#word").val(),
        sentence: $("#sentence").val()
      }, function(responseText) {
        return $(".message").text(responseText);
      });
    });
  };

  $(function() {
    $("#category_name").Watermark("New Category Name");
    $("#word").Watermark("Word");
    $("#sentence").Watermark("Sentence");
    init_categories();
    $("#create_category").click(function() {
      return create_category();
    });
    $("#category_list").change(function() {
      var cat, cat_id;
      cat = $("#category_list option:selected").text();
      cat_id = $("#category_list").val();
      return chrome.storage.sync.set({
        cat: cat,
        cat_id: cat_id
      }, function() {
        return $(".message").text("destination is set to " + cat + ".");
      });
    });
    $("#search").click(function() {
      return word_search();
    });
    $('#word').keypress(function(e) {
      if (e.keyCode === 13) {
        return word_search();
      }
    });
    return $('#sentence').keypress(function(e) {
      if (e.keyCode === 13) {
        return word_search();
      }
    });
  });

}).call(this);
