// Generated by CoffeeScript 1.9.3
(function() {
  describe("RegisterController", function() {
    var $location, FlashService, UserService, vm;
    vm = UserService = $location = FlashService = null;
    beforeEach(module("app"));
    beforeEach(inject(function(_UserService_, _$location_, _FlashService_, _$controller_) {
      var ref;
      ref = [_UserService_, _$location_, _FlashService_], UserService = ref[0], $location = ref[1], FlashService = ref[2];
      return vm = _$controller_("RegisterController");
    }));
    return describe("vm.user", function() {
      return it("", function() {});
    });
  });

}).call(this);
