// Generated by CoffeeScript 1.9.3
(function() {
  var myFileUpload;

  myFileUpload = function($parse) {
    return {
      restrict: "A",
      link: function(scope, element, attrs) {
        return element.bind("change", function() {
          return scope.$apply(function() {
            return $parse(attrs.myFileUpload).assign(scope, element[0].files[0]);
          });
        });
      }
    };
  };

  myFileUpload.$inject = ["$parse"];

  angular.module('app').directive("myFileUpload", myFileUpload);

}).call(this);
