// Generated by CoffeeScript 1.9.3
(function() {
  var dataURLtoBlob;

  dataURLtoBlob = function(dataurl) {
    var arr, bstr, mime, n, u8arr;
    arr = dataurl.split(',');
    mime = arr[0].match(/:(.*?);/)[1];
    bstr = atob(arr[1]);
    n = bstr.length;
    u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], {
      type: mime
    });
  };

  chrome.runtime.onMessage.addListener(function(request, sender, callback) {
    var fd, xhr;
    if (request.type === "contentScript: lookUpWord") {
      fd = new FormData();
      fd.append("key", request.key);
      xhr = new XMLHttpRequest();
      xhr.open("POST", request.url, true);
      xhr.onload = function() {
        return callback(xhr.responseText);
      };
      xhr.onerror = function() {
        return callback("failure");
      };
      xhr.send(fd);
    } else if (request.type === "contentScript: lookUpEijiro") {
      xhr = new XMLHttpRequest();
      xhr.open("POST", request.url, true);
      xhr.onload = function() {
        return callback(xhr.responseText);
      };
      xhr.onerror = function() {
        return callback("failure");
      };
      xhr.send();
      console.log("--- request send");
    } else if (request.type === "contentScript: shootAndUpload") {
      chrome.tabs.captureVisibleTab(function(dataurl) {
        console.log("--- captured");
        console.log(dataurl);
        return chrome.storage.sync.get({
          cat: "uncategorized",
          cat_id: 8
        }, function(items) {
          fd = new FormData();
          fd.append("picture", dataURLtoBlob(dataurl), "hello.jpg");
          fd.append("word", request.word);
          fd.append("sentence", request.sentence);
          fd.append("meaning", request.meaning);
          fd.append("cat_id", items.cat_id);
          xhr = new XMLHttpRequest();
          xhr.open("POST", request.url, true);
          xhr.onload = function() {
            return callback(xhr.responseText);
          };
          xhr.onerror = function() {
            return callback("failure");
          };
          return xhr.send(fd);
        });
      });
    }
    return true;
  });

}).call(this);
