// Generated by CoffeeScript 1.9.3
(function() {
  var AuthService;

  AuthService = function($resource) {
    return $resource("/api/sessions/:token", {
      token: "@id"
    }, {
      create: {
        method: "POST"
      },
      destroy: {
        method: "DELETE"
      }
    });
  };

  AuthService.$inject = ["$resource"];

  angular.module("app").factory("AuthService", AuthService);

}).call(this);
