// Generated by CoffeeScript 1.9.3
(function() {
  var AuthService;

  AuthService = function($resource, $cookies) {
    var r, service, session;
    r = $resource("/api/sessions/:token", {
      token: "@id"
    }, {
      create: {
        method: "POST"
      },
      destroy: {
        method: "DELETE"
      }
    });
    session = $cookies.getObject("session") || null;
    service = {
      login: function(user) {
        return r.create(user).$promise.then(function(data) {
          session = {
            userId: data.user.id,
            token: data.user.auth_token
          };
          return $cookies.putObject("session", session);
        });
      },
      logout: function() {
        return r.destroy({
          token: session.token
        }).$promise.then(function() {
          session = null;
          return $cookies.putObject("session", session);
        });
      },
      getSession: function() {
        return session;
      }
    };
    return service;
  };

  AuthService.$inject = ["$resource", "$cookies"];

  angular.module("app").factory("AuthService", AuthService);

}).call(this);
