// Generated by CoffeeScript 1.9.3
(function() {
  var CategoryService;

  CategoryService = function(AuthService, $resource) {
    var r, service;
    r = $resource("/api/categories/:categoryId", {
      categoryId: "@id"
    }, {
      index: {
        method: "GET"
      },
      create: {
        method: "POST"
      },
      update: {
        method: "PUT",
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      },
      destroy: {
        method: "DELETE",
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      }
    });
    service = {
      index: function() {
        return r.index().$promise;
      },
      create: function(category) {
        return r.create(category).$promise;
      },
      update: function(category) {
        return r.update(category).$promise;
      },
      destroy: function() {
        return r.destroy().$promise;
      }
    };
    return service;
  };

  CategoryService.$inject = ["AuthService", "$resource"];

  angular.module("app").factory("CategoryService", CategoryService);

}).call(this);
