// Generated by CoffeeScript 1.9.3
(function() {
  var FlashService;

  FlashService = function($rootScope) {
    var currentMassage, currentStatus, keepedMessage, keepedStatue, service;
    currentMassage = "";
    currentStatus = "";
    keepedMessage = "";
    keepedStatue = "";
    $rootScope.$on("$routeChangeSuccess", function() {
      var currentMessage, keepedStatus;
      currentMessage = keepedMessage;
      currentStatus = keepedStatus;
      keepedMessage = "";
      return keepedStatus = "none";
    });
    service = {
      getStatus: function() {
        return currentStatus;
      },
      getMessage: function() {
        return currentMessage;
      },
      set: function(message, status) {
        keepedMessage = message;
        return keepedStatue = status;
      }
    };
    return service;
  };

  FlashService.$inject = ["$rootScope"];

  angular.module("app").factory("FlashService", FlashService);

}).call(this);
