// Generated by CoffeeScript 1.9.3
(function() {
  var FlashService;

  FlashService = function($rootScope, $timeout) {
    var apply, currentMessage, currentStatus, keepedMessage, keepedStatus, service;
    currentMessage = "";
    currentStatus = "";
    keepedMessage = "";
    keepedStatus = "";
    apply = function() {
      currentMessage = keepedMessage;
      currentStatus = keepedStatus;
      keepedMessage = "";
      keepedStatus = "";
      return $timeout(function() {
        currentMessage = "";
        return currentStatus = "";
      }, 2000);
    };
    $rootScope.$on("$routeChangeSuccess", function() {
      return $timeout((function() {
        return apply();
      }), 10);
    });
    service = {
      getStatus: function() {
        return currentStatus;
      },
      getMessage: function() {
        return currentMessage;
      },
      set: function(message, status) {
        keepedMessage = message;
        return keepedStatus = status;
      },
      apply: function() {
        return apply();
      }
    };
    return service;
  };

  FlashService.$inject = ["$rootScope", "$timeout"];

  angular.module("app").factory("FlashService", FlashService);

}).call(this);
