// Generated by CoffeeScript 1.9.3
(function() {
  var FlashService;

  FlashService = function($rootScope) {
    var apply, currentMessage, currentStatus, keepedMessage, keepedStatus, service;
    currentMessage = "";
    currentStatus = "";
    keepedMessage = "";
    keepedStatus = "";
    apply = function() {
      currentMessage = keepedMessage;
      currentStatus = keepedStatus;
      keepedMessage = "";
      return keepedStatus = "";
    };
    $rootScope.$on("$routeChangeSuccess", function() {
      return apply();
    });
    service = {
      getStatus: function() {
        return currentStatus;
      },
      getMessage: function() {
        return currentMessage;
      },
      set: function(message, status) {
        keepedMessage = message;
        return keepedStatus = status;
      },
      apply: apply
    };
    return service;
  };

  FlashService.$inject = ["$rootScope"];

  angular.module("app").factory("FlashService", FlashService);

}).call(this);
