// Generated by CoffeeScript 1.9.3
(function() {
  var ItemService;

  ItemService = function(AuthService, $resource) {
    var r, service;
    r = $resource("/api/items/:itemId", {
      itemId: "@itemId"
    }, {
      index: {
        method: "GET",
        transformResponse: function(data) {
          return data.items;
        },
        isArray: true
      },
      create: {
        method: "POST",
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      },
      update: {
        method: "PUT",
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      },
      destroy: {
        method: "DELETE",
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      }
    });
    service = {
      index: function() {
        return r.index();
      },
      create: function(item) {
        return r.create({
          category_id: item.category.id,
          item: _(item).pick(["word", "sentence", "meaning", "picture"])
        });
      },
      update: function(item) {
        return r.update({
          itemId: item.id
        }, {
          category_id: item.category.id,
          item: _(item).pick(["word", "sentence", "meaning", "picture"])
        });
      },
      destroy: function(item) {
        return r.destroy({
          itemId: item.id
        }, {
          category_id: item.category.id
        });
      }
    };
    return service;
  };

  ItemService.$inject = ["AuthService", "$resource"];

  angular.module("app").factory("ItemService", ItemService);

}).call(this);
