// Generated by CoffeeScript 1.9.3
(function() {
  var UserService;

  UserService = function(AuthService, $resource) {
    var r, service;
    r = $resource("/api/users/:userId", {
      userId: "@id"
    }, {
      show: {
        method: "GET",
        params: {
          userId: function() {
            return AuthService.getSession().userId;
          }
        },
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      },
      create: {
        method: "POST"
      },
      update: {
        method: "PUT",
        params: {
          userId: function() {
            return AuthService.getSession().userId;
          }
        },
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      },
      destroy: {
        method: "DELETE",
        params: {
          userId: function() {
            return AuthService.getSession().userId;
          }
        },
        headers: {
          Authorization: function() {
            return AuthService.getSession().token;
          }
        }
      }
    });
    service = {
      show: function() {
        return r.show().$promise;
      },
      create: function(user) {
        return r.create(user).$promise;
      },
      update: function(user) {
        return r.update(user).$promise;
      },
      destroy: function() {
        return r.destroy().$promise;
      }
    };
    return service;
  };

  UserService.$inject = ["AuthService", "$resource"];

  angular.module("app").factory("UserService", UserService);

}).call(this);
