// Generated by CoffeeScript 1.9.3
(function() {
  var CategoryController;

  CategoryController = function(CategoryService, UserService, AuthService, FlashService, $location) {
    var vm;
    vm = this;
    vm.flash = FlashService;
    vm.categories = CategoryService.index();
    vm.sum_items = function(cs) {
      return _.foldl(vm.categories, (function(n, c) {
        return n + c.item_ids.length;
      }), 0);
    };
    vm.showForm = function(category) {
      vm.editing = !!category;
      vm.formOn = true;
      return vm.categoryForm = _.clone(category);
    };
    vm.submit = function() {
      var p;
      vm.dataLoading = true;
      p = vm.editing ? CategoryService.update(vm.categoryForm) : CategoryService.create(vm.categoryForm);
      return p.$promise.then(function() {
        FlashService.set("Successfully Submitted", "success");
        vm.dataLoading = false;
        FlashService.apply();
        return vm.formOn = false;
      }, function() {
        FlashService.set("Submit failed", "danger");
        vm.dataLoading = false;
        FlashService.apply();
        return vm.formOn = false;
      });
    };
    vm.deleteCategory = function(category) {
      return CategoryService.destroy(category);
    };
    vm.user = UserService.show();
    vm["delete"] = function() {
      vm.dataLoading = true;
      return UserService.destroy().then(function() {
        FlashService.set("Account Deleted", "success");
        return $location.path("/register");
      }, function() {
        vm.dataLoading = false;
        FlashService.set("Account deletion failed", "danger");
        return FlashService.apply();
      });
    };
    vm.logout = function() {
      vm.dataLoading = true;
      return AuthService.logout().then(function() {
        FlashService.set("Logout successful", "success");
        return $location.path("/login");
      }, function() {
        vm.dataLoading = false;
        FlashService.set("Logout failed", "danger");
        return FlashService.apply();
      });
    };
  };

  CategoryController.$inject = ["CategoryService", "UserService", "AuthService", "FlashService", "$location"];

  angular.module("app").controller("CategoryController", CategoryController);

}).call(this);
