// Generated by CoffeeScript 1.9.3
(function() {
  var CategoryController;

  CategoryController = function(CategoryService, UserService, AuthService, FlashService, $location) {
    var vm;
    vm = this;
    CategoryService.index().$promise.then(function(data) {
      return vm.categories = data.categories;
    });
  };

  CategoryController.$inject = ["CategoryService", "UserService", "AuthService", "FlashService", "$location"];

  angular.module("app").controller("CategoryController", CategoryController);

}).call(this);
