// Generated by CoffeeScript 1.9.3
(function() {
  var HomeController;

  HomeController = function($rootScope) {
    return this.test = "HomeController is working";
  };

  HomeController.$inject = ['$rootScope'];

  angular.module("app").controller('HomeController', HomeController);

}).call(this);
