// Generated by CoffeeScript 1.9.3
(function() {
  var HomeController;

  HomeController = function() {};

  HomeController.$inject = [];

  angular.module("app").controller('HomeController', HomeController);

}).call(this);
