// Generated by CoffeeScript 1.9.3
(function() {
  var LoginController;

  LoginController = function() {};

  LoginController.$inject = [];

  angular.module("app").controller('LoginController', LoginController);

}).call(this);
