// Generated by CoffeeScript 1.9.3
(function() {
  var LoginController;

  LoginController = function(AuthService, $location, FlashService) {
    var onError, onSuccess, vm;
    vm = this;
    vm.flash = FlashService;
    vm.user = {
      email: "hiogawa@hiogawa",
      password: "12345678"
    };
    onSuccess = function(data) {
      console.log(data.auth_token);
      FlashService.set("Login successful", "success");
      $location.path("/");
      return console.log;
    };
    onError = function(err) {
      console.log(err);
      FlashService.set("Login failed, please try again", "danger");
      vm.dataLoading = false;
      return FlashService.apply();
    };
    vm.login = function() {
      vm.dataLoading = true;
      return AuthService.create(vm.user, onSuccess, onError);
    };
  };

  LoginController.$inject = ["AuthService", "$location", "FlashService"];

  angular.module("app").controller('LoginController', LoginController);

}).call(this);
