// Generated by CoffeeScript 1.9.3
(function() {
  var RegisterController;

  RegisterController = function(UserService, $location, FlashService) {
    var onError, onSuccess, vm;
    vm = this;
    vm.flash = FlashService;
    vm.user = {
      email: "hiogawa@hiogawa",
      password: "12345678",
      password_confirmation: "12345678"
    };
    onSuccess = function(data) {
      console.log(data);
      FlashService.set("Registration successful", "success");
      return $location.path("/login");
    };
    onError = function(err) {
      console.log(err);
      FlashService.set("Registration failed, please try again", "danger");
      vm.dataLoading = false;
      return FlashService.apply();
    };
    vm.register = function() {
      vm.dataLoading = true;
      return UserService.create(vm.user, onSuccess, onError);
    };
  };

  RegisterController.$inject = ["UserService", "$location", "FlashService"];

  angular.module("app").controller("RegisterController", RegisterController);

}).call(this);
