// Generated by CoffeeScript 1.9.3
(function() {
  var UpdateController;

  UpdateController = function(UserService, $location, FlashService) {
    var vm;
    vm = this;
    vm.flash = FlashService;
    vm.user = {
      email: "hiogawa@hiogawa",
      password: "12345678",
      password_confirmation: "12345678"
    };
    vm.submit = function() {
      vm.dataLoading = true;
      return UserService.update(vm.user).then(function() {
        FlashService.set("Account updated", "success");
        return $location.path("/");
      }, function() {
        FlashService.set("Account update failed", "danger");
        vm.dataLoading = false;
        return FlashService.apply();
      });
    };
  };

  UpdateController.$inject = ["UserService", "$location", "FlashService"];

  angular.module("app").controller("UpdateController", UpdateController);

}).call(this);
