// Generated by CoffeeScript 1.9.3
(function() {
  var $ext_div0, $ext_div1, $ext_ul, $input0, $input1, DELAY, clicks, lookUpWord, shootAndUpload, timer;

  $ext_div0 = $("<div>").attr("id", "ext_div0");

  $input0 = $("<input>").attr("id", "word");

  $input1 = $("<input>").attr("id", "sentence");

  $ext_div1 = $("<div>").attr("id", "ext_div1");

  $ext_ul = $("<ul>");

  $("body").append($ext_div0.append($input0).append($input1)).append($ext_div1.append($ext_ul));

  $ext_div1.hide();

  $ext_div1.dblclick(function() {
    $input0.val("");
    $input1.val("");
    return $ext_div1.hide();
  });

  DELAY = 200;

  clicks = 0;

  timer = null;

  $('body').on('mouseup', function(e) {
    var w;
    if (e.altKey || e.shiftKey) {
      return;
    }
    clicks++;
    w = window.getSelection().toString().trim();
    if (w === '') {
      return;
    }
    if (clicks === 1) {
      timer = setTimeout((function() {
        $input0.val(($input0.val().trim() === "" ? w : ($input0.val()) + " " + w));
        $input1.val(window.getSelection().getRangeAt(0).startContainer.parentNode.textContent);
        clicks = 0;
      }), DELAY);
    } else {
      clearTimeout(timer);
      $input0.val(($input0.val()) + " " + w);
      $input1.val(window.getSelection().getRangeAt(0).startContainer.parentNode.textContent);
      clicks = 0;
    }
  }).on('dblclick', function(e) {
    return e.preventDefault();
  });

  lookUpWord = function() {
    var req_url, s, voc;
    console.log('--- LookUpWord');
    console.log(voc = $input0.val().trim());
    console.log(s = $input1.val().trim());
    if (voc === '') {
      return;
    }
    req_url = "http://www.dictionaryapi.com/api/v1/references/collegiate/xml/" + (encodeURIComponent(voc));
    return chrome.runtime.sendMessage({
      type: 'contentScript: lookUpWord',
      url: req_url,
      key: 'c4c815db-b3ae-4d2f-8e31-2e556ec300bd'
    }, function(responseText) {
      var l, xml;
      $ext_ul.empty();
      console.log('-- LookUpWord : got response --');
      console.log(responseText);
      if (responseText === 'failure') {
        return;
      }
      xml = $.parseXML(responseText);
      if ($(xml).find('dt').size() !== 0) {
        $(xml).find('dt').each(function() {
          return $ext_ul.append($('<li>').text($(this).text()));
        });
      } else {
        $(xml).find('suggestion').each(function() {
          return $ext_ul.append($('<li>').text($(this).text()));
        });
      }
      $ext_div1.show();
      if ($('.div-alc #alc').length !== 0) {
        l = 'http://eow.alc.co.jp/search?q=' + voc;
        $('.div-alc #alc').attr('src', l);
        return $('.div-alc #alc').load(function() {
          return $('.div-alc').scrollTop(350);
        });
      }
    });
  };

  shootAndUpload = function() {
    console.log('--- shootAndUpload');
    return chrome.runtime.sendMessage({
      type: 'contentScript: shootAndUpload',
      url: 'http://often-test-app.xyz:3005/posts/iphone',
      word: $input0.val().trim(),
      sentence: $input1.val().trim()
    }, function(responseText) {
      console.log('-- shootAndUpload : got response --');
      console.log(responseText);
      if (responseText === 'you got it uploaded\n') {
        $ext_ul.prepend($('<li>').text('you got it.'));
        $input0.val('');
        return $input1.val('');
      } else {
        return $ext_ul.prepend($('<li>').text('not good.'));
      }
    });
  };

  $(document).keydown(function(e) {
    if (e.altKey && e.shiftKey && e.which === 83) {
      console.log('--- alt shift 83 ---');
      return shootAndUpload();
    } else if (e.altKey && e.which === 83) {
      console.log('--- alt 83 ---');
      return lookUpWord();
    }
  });

  chrome.runtime.onMessage.addListener(function(request, sender, callback) {
    if (request.type === "popup: word_search") {
      console.log(request.type);
      console.log(request.word);
      console.log($input0.val(request.word));
      console.log($input1.val(request.sentence));
      lookUpWord();
      return callback("contentScript: message received, over.");
    }
  });

}).call(this);
