// Generated by CoffeeScript 1.9.3
(function() {
  var config;

  config = function($routeProvider, $locationProvider) {
    return $routeProvider.when("/", {
      controller: "HomeController",
      templateUrl: "templates/home.html"
    });
  };

  config.$inject = ["$routeProvider", "$locationProvider"];

  angular.module('app').config(config);

}).call(this);
