// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var csss, jss;
    console.log("it's from popup.coffee");
    csss = ['lib/my_bootstrap_container.css', 'contentScript/contentScript.css'];
    jss = ['lib/jquery.js', 'lib/bootstrap.js', 'lib/underscore.js', 'lib/backbone.js', 'contentScript/backbone/app.js', 'contentScript/contentScript.js'];
    csss.forEach(function(css) {
      return chrome.tabs.insertCSS({
        file: css
      });
    });
    return jss.forEach(function(js) {
      return chrome.tabs.executeScript({
        file: js
      });
    });
  });

}).call(this);
