// Generated by CoffeeScript 1.9.3
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender, callback) {
    var fd;
    switch (request.type) {
      case "ajax":
        if (request.settings.data != null) {
          fd = new FormData;
          _.mapObject(request.settings.data, function(val, key) {
            if (key === "picture") {
              return fd.append(key, extLib.dataURLtoBlob(val));
            } else {
              return fd.append(key, val);
            }
          });
          request.settings.data = fd;
        }
        Promise.resolve($.ajax(request.settings)).then(function(data) {
          if (request.settings.dataType === "xml") {
            callback({
              status: "success",
              data: (new XMLSerializer()).serializeToString(data)
            });
          }
          return callback({
            status: "success",
            data: data
          });
        })["catch"](function(err) {
          return callback({
            status: "error",
            data: err
          });
        });
        break;
      case "captureVisibleTab":
        chrome.tabs.captureVisibleTab(function(dataurl) {
          return callback({
            status: "success",
            data: dataurl
          });
        });
        setTimeout((function() {
          return callback({
            status: "error"
          });
        }), 1000);
    }
    return true;
  });

}).call(this);
