// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = {};

  app.LocalData = Backbone.Model.extend({
    localStorage: new Backbone.LocalStorage("ext-local-data"),
    defaults: {
      id: 0
    }
  });

  app.localData = new app.LocalData();

  app.Category = Backbone.Model;

  app.Categories = Backbone.Collection.extend({
    model: app.Category,
    url: chrome.extension.getURL("contentScript/backbone/sampleAPI/categories.json")
  });

  app.categories = new app.Categories();

  app.CategoriesView = Backbone.View.extend({
    tagName: "div",
    className: "input-group input-group-sm",
    initialize: function() {
      this.collection = app.categories;
      this.collection.on("sync", this.render, this);
      app.localData.on("change", this.render, this);
      this.collection.fetch();
      return app.localData.fetch();
    },
    render: function() {
      console.log(app.localData.toJSON());
      this.template = _.template($("#ext-categories-t").html());
      this.$el.html(this.template({
        categories: this.collection.toJSON(),
        current: app.localData.toJSON()
      }));
      return $('.dropdown-toggle').dropdown();
    },
    events: function() {
      return {
        "click .dropdown-menu a": function(e) {
          return app.localData.save({
            exists: true,
            name: $(e.currentTarget).text(),
            categoryId: $(e.currentTarget).attr("data-id")
          });
        }
      };
    }
  });

  app.DictionaryView = Backbone.View.extend({
    tagName: "div",
    className: "ext-dictionary panel",
    initialize: function(data) {
      this.template = _.template($("#ext-dictionary-t").html());
      this.$el.html(this.template({
        data: data
      }));
      this.$popovers = this.$('[data-toggle="popover"]');
      return this.initPopover();
    },
    events: {
      "click .remove": "remove",
      "mouseleave": function() {
        return this.$popovers.popover('hide');
      },
      "mouseover [data-toggle='popover']": function(e) {
        return $(e.currentTarget).popover('show');
      },
      "show.bs.popover [data-toggle='popover']": function(e) {
        return this.$popovers.not($(e.currentTarget)).popover('hide');
      },
      "click .suggestion": function(e) {
        app.appView.$inputWord.val($(e.currentTarget).text());
        return app.appView.searchWord();
      }
    },
    initPopover: function() {
      return this.$popovers.each(function() {
        var $popoverContent;
        $popoverContent = $(this).next().clone();
        $popoverContent.find(".meaning").click(function() {
          return app.appView.$inputMeaning.val($(this).text());
        });
        $(this).popover({
          content: $popoverContent
        });
        return $(this).next().remove();
      });
    }
  });

  app.AppView = Backbone.View.extend({
    initialize: function() {
      this.$dictionaries = this.$("#ext-dictionaries");
      this.$inputWord = this.$("#ext-word");
      this.$inputSentence = this.$("#ext-sentence");
      this.$inputMeaning = this.$("#ext-meaning");
      this.categoryId = void 0;
      this.renderCategories();
      return $('body').dblclick((function(_this) {
        return function(e) {
          var s, w;
          w = window.getSelection().toString().trim();
          s = window.getSelection().getRangeAt(0).startContainer.parentNode.textContent.trim();
          _this.$inputWord.val((_this.$inputWord.val() + " " + w).trim());
          _this.$inputSentence.val(s);
          _this.$inputWord.focus();
          return _this.searchWord();
        };
      })(this));
    },
    renderCategories: function() {
      app.categoriesView = new app.CategoriesView();
      return this.$("#ext-settings").append(app.categoriesView.$el);
    },
    events: {
      "keypress #ext-word": function(e) {
        if (e.which === 13) {
          return this.searchWord();
        }
      },
      "click .upload": "upload"
    },
    upload: function() {
      return extLib.tabCapture()["catch"](function(err) {
        return console.log("error - AppView.upload: " + err);
      }).then((function(_this) {
        return function(dataurl) {
          var data;
          data = {
            picture: dataurl,
            word: _this.$inputWord.val(),
            sentence: _this.$inputSentence.val(),
            meaning: _this.$inputMeaning.val(),
            category_id: _this.categoryId
          };
          return extLib.ultraAjax({
            url: "http://localhost:4567/upload",
            type: "POST",
            data: data,
            processData: false,
            contentType: false
          })["catch"](function(err) {
            return console.log("error: AppView.upload - " + err);
          }).then(function(data) {
            return console.log(data);
          });
        };
      })(this));
    },
    searchWord: function() {
      var word;
      word = this.$inputWord.val().trim();
      if (word !== "") {
        this.$dictionaries.empty();
        extLib.Eijiro(word)["catch"](function(err) {
          return console.log("error in eijiro: " + err);
        }).then((function(_this) {
          return function(data) {
            if (_this.eijiroView != null) {
              _this.eijiroView.remove();
            }
            _this.eijiroView = new app.DictionaryView(data);
            return _this.$dictionaries.append(_this.eijiroView.$el);
          };
        })(this));
        return extLib.DictionaryAPI(word)["catch"](function(err) {
          return console.log("error in dicAPI: " + err);
        }).then((function(_this) {
          return function(data) {
            if (_this.dAPIView != null) {
              _this.dAPIView.remove();
            }
            _this.dAPIView = new app.DictionaryView(data);
            return _this.$dictionaries.append(_this.dAPIView.$el);
          };
        })(this));
      }
    }
  });

  $.get(chrome.extension.getURL("contentScript/contentScript.html"), function(html) {
    var $extWrapper;
    $extWrapper = $(html);
    $('body').append($extWrapper);
    return app.appView = new app.AppView({
      el: $extWrapper
    });
  });

}).call(this);
