// Generated by CoffeeScript 1.9.3
(function() {
  var MyStorage, root;

  MyStorage = Backbone.Model.extend({
    initialize: function() {
      return this.items = {};
    },
    init: function() {
      return chrome.storage.sync.get((function(_this) {
        return function(items) {
          _(_this.items).extend(items);
          return _this.trigger("update", _this.items);
        };
      })(this));
    },
    getData: function() {
      return this.items;
    },
    clear: function() {
      return chrome.storage.sync.clear((function(_this) {
        return function() {
          _this.items = {};
          return _this.trigger("update", _this.items);
        };
      })(this));
    },
    update: function(items) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          chrome.storage.sync.set(items, function() {
            _(_this.items).extend(items);
            _this.trigger("update", _this.items);
            return resolve(_this.items);
          });
          return setTimeout((function() {
            return reject("lib.storageSet timeout");
          }), 1000);
        };
      })(this));
    }
  });

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.MyStorage = MyStorage;

}).call(this);
